### ISSUE TITLE
Can't change default texts

### ISSUE THREAD

**Issue by maribelmai** [hotchemi/Android-Rate#36]
Hello. First of all, thank you very much for the library.
I'm having an issue trying to change the default texts. I override the "rate_dialog_message" but the dialog is still showing the default message. Do you know what can be happenning?
Thanks!
Maribel

**Comment by muratogat** [comment]
Overriding the general strings.xml in values folder does not override the default texts. I had to create values-tr folder and another strings.xml to override the Turkish default text. Then it worked.

**Comment by hotchemi** [comment]
Exactly. It depends on the locale of each devices.
Android framework manages it well.
