### ISSUE TITLE
 AlertDialog buttons doesn't fit in dialog box on Android 5.0

### ISSUE THREAD

**Issue by Bersh** [hotchemi/Android-Rate#40]
I've noticed that on Android 5.0 buttons in AlertDialog doesn't fit in dialog box. Similar problem described here: http://stackoverflow.com/questions/26708976/alert-dialog-buttons-problems-in-android-l
Unfortunately I don't have solution for this except of using custom layout for AlertDialog. <br/>
Here is few examples how does the problem looks like: <br/>
![screenshot_2014-12-14-16-49-16](https://cloud.githubusercontent.com/assets/1333114/5427814/4f9144ba-83b6-11e4-8cdb-c7756922ef63.png)
![screenshot_2014-12-14-17-20-34](https://cloud.githubusercontent.com/assets/1333114/5427815/4f99caa4-83b6-11e4-8258-e0bbd46e6033.png)

**Comment by hotchemi** [comment]
https://code.google.com/p/android/issues/detail?id=78302

**Comment by hotchemi** [comment]
http://stackoverflow.com/questions/27187353/dialog-buttons-with-long-text-not-wrapping-squeezed-out-material-theme-on-an

**Comment by matteinn** [comment]
Any fix for this issue?

**Comment by hotchemi** [comment]
@maarekj 
Sorry for the delay.
May be this is the default requirements of the android framework.
If you want to solve the problem, you can set `buttonBarButtonStyle` in your theme to point to a style that extends `Widget.Material.Button.Borderless.Colored` and adds whatever attributes you need.

**Comment by hotchemi** [comment]
```xml
<resources>
    <style name="AppBaseTheme" parent="android:Theme.Material.Light">
        <!-- AlertDialog Style override in order to try to fix non line breaking buttons -->
        <item name="android:alertDialogTheme">@style/CustomAlertDialogStyle</item>
    </style>  

    <style name="CustomAlertDialogStyle" parent="android:Theme.Material.Light.Dialog.Alert">
        <item name="android:buttonBarButtonStyle">@style/CustomButtonBarButtonStyle</item>
        <item name="android:buttonBarStyle">@style/CustomButtonBarStyle</item>
    </style>

    <style name="CustomButtonBarStyle" parent="@android:style/Widget.Material.Light.ButtonBar.AlertDialog">
        <!-- Making sure, the button bar uses parent width and is not restricted in height -->
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:height">@null</item>
        <item name="android:minHeight">@null</item>
    </style>

    <style name="CustomButtonBarButtonStyle" parent="@android:style/Widget.Material.Light.Button.Borderless.Colored">
        <!-- Setting the weight as follows should result in equally wide buttons filling the alert dialog width,
            but instead they span further out of the dialog, breaking in multiple lines though -->
        <item name="android:layout_width">0dp</item>
        <item name="android:layout_weight">1</item>
        <!-- setting a fixed width as follows results in narrow buttons with line breaks, but of course this is not a solution -->
        <!-- <item name="android:width">100dp</item> -->
    </style>

</resources>
```

**Comment by maarekj** [comment]
Why I was tagged ?

**Comment by hotchemi** [comment]
@maarekj Sorry, my mistake...

**Comment by matteinn** [comment]
Thank you @hotchemi .

**Comment by hotchemi** [comment]
@Bersh @matteinn 
I will fix this problem at ver 0.5.0. Stay tune:)

![](http://i.gyazo.com/3a98b8f839cac89a0f4b4b9f02789aa5.png)

**Comment by matteinn** [comment]
Coil, thanks!

--

**Comment by ollyde** [comment]
Any traction on this, it's not working currently (49)

**Comment by AlexanderLS** [comment]
@voidstarfire it's working on https://github.com/Vorlonsoft/AndroidRate
