### ISSUE TITLE
Different dialog themes

### ISSUE THREAD

**Issue by JoelReeves** [hotchemi/Android-Rate#51]
First off great library!  :)

I was wondering if you were going to change the style of the dialog to conform to the new Material Design dialogs. Or if you could give us a choice in the builder to choose between Holo and Material Design themes.

    AppRate.with(this)
        .theme(AppRate.Theme_Holo_Dark) // or something similiar

**Comment by hotchemi** [comment]
Oh, cool. I'd like to implement like that:)

**Comment by hotchemi** [comment]
@JoelReeves 
I've been thinking using android.support.v7.app.AlertDialog, but it has critical bug like [this](http://stackoverflow.com/questions/26708976/alert-dialog-buttons-problems-in-android-l).
So I will implement this feature after this bug will be fixed.
Of course u can use Material style in Lollipop devices.

![](http://i.gyazo.com/3a98b8f839cac89a0f4b4b9f02789aa5.png)
