### ISSUE TITLE
Add function to change dialog text

### ISSUE THREAD

**Issue by sagits** [hotchemi/Android-Rate#69]
Hi, would you add a function to change the dialog details text? We can change all texts, except this one. I know i can change it using res, but i would have to create separated files (strings-pt, strings-us) just to change a single line. 

Thanks in advance.

**Comment by hotchemi** [comment]
Hi, do you mean [DialogOptions.setMessageResId](https://github.com/hotchemi/Android-Rate/blob/master/library/src/main/java/hotchemi/android/rate/DialogOptions.java#L63)?

**Comment by sagits** [comment]
Yes, thanks. I was searching for something like setTextMessageResId() because all other methods follow this convention.

**Comment by hotchemi** [comment]
@sagits Sure! and I'm sorry about I've not prepared enough documents...I'm gonna do that in the near future:) Feel free to ask me something.
