### ISSUE TITLE
Buttons being shown in the vertical orientation on Marshmallow

### ISSUE THREAD

**Issue by daividssilverio** [hotchemi/Android-Rate#72]
Hi there. I'm using version 0.5.3.
It seems there is a bug with this library when using Marshmallow. The buttons for the dialog are being stacked, just like if they are in a linearlayout with the orientation set to horizontal.

Running your sample app.
![device-2015-10-13-163807](https://cloud.githubusercontent.com/assets/2173493/10467631/ddcbada0-71c8-11e5-8afd-c1ccf261d958.png)

**Comment by hotchemi** [comment]
Thx, I'm gonna investigate it.

**Comment by daividssilverio** [comment]
Thanks!
It seems to be a problem with the styles applied to the Alert Dialog and the ButtonBar on the AlertDialog... I've overridden these styles on API>21 as an temporary workaround for the project I'm working.

    <style name="CustomLollipopDialogStyle" parent="android:Theme.Material.Light.Dialog.Alert">
    </style>
    <style name="CustomButtonBarStyle" parent="@android:style/Widget.Material.Light.ButtonBar.AlertDialog">
    </style>
    <style name="CustomButtonBarButtonStyle" parent="@android:style/Widget.Material.Light.Button.Borderless.Colored">
    </style>

**Comment by hotchemi** [comment]
Yeah it's actually the fix for lollipop bug.
http://stackoverflow.com/questions/26708976/alert-dialog-buttons-problems-in-android-l
I should change to adopt it only API level 21 and 22.

**Comment by hotchemi** [comment]
Fixed and pushed.

**Comment by thinkpozzitive** [comment]
hotchemi: version 0.5.5 still has this behavior on android marshmallow. The buttons are still vertically stacked.

**Comment by hotchemi** [comment]
@thinkpozzitive Could u show the sample? I tested in sample module but it did not occur.

**Comment by thinkpozzitive** [comment]
So it seems that because I was using a app theme which was a parent of AppCompat and because I was applying a background color to the alert dialog which had a parent of Theme.AppCompat.Dialog.Alert I was experiencing the issue above. 

All I had to do what to point my customization of the alert dialog to a similar style like yours (and switch from parent="Theme.AppCompat.Dialog.Alert" to parent="android:Theme.Material.Dialog.Alert") where I only added and additional item for the windowbackground.

**Comment by hotchemi** [comment]
@thinkpozzitive Umm could u give me a pull request?

**Comment by pdavid0** [comment]
I know it an old thread but I have the same problem with Android N and I am not using custom themes for the dialog.

Sohuld I open a new issue ?

**Comment by JEKos** [comment]
Same problem here for 6.0 version

**Comment by OneManStudioDotSe** [comment]
Did you find a solution to this problem? I still have it with the latest version of the library running on Android 8.1.

**Comment by navczydev** [comment]
it's still there tested @android9
