### ISSUE TITLE
Add support for custom dialog texts

### ISSUE THREAD

**Issue by urgas9** [hotchemi/Android-Rate#76]
Is there any possibility to add an option to set custom strings at runtime? I have translations on the server, so i cannot use strings.xml. 

Thanks.

**Comment by hotchemi** [comment]
@urgas9 Could u manage the problem with below issue?
https://github.com/hotchemi/Android-Rate/issues/69

**Comment by urgas9** [comment]
Unfortunately not. I would need a functions like setMessageString(String message), setTitleString(String title)... As i get the content from a RESTful API

**Comment by hotchemi** [comment]
Ah ic. So could u submit a pull request?

**Comment by urgas9** [comment]
Right now i don't have any time to implement this, but i will try to find some in the near future. That would be a great addition to a great library IMO...

**Comment by hotchemi** [comment]
OK

**Comment by urgas9** [comment]
Pull request sent...
