### ISSUE TITLE
Use android.support.v7.app.AlertDialog instead of android.app.AlertDialog

### ISSUE THREAD

**Issue by RomainPiel** [hotchemi/Android-Rate#85]
Between honeycomb and lollipop, the `AlertDialog` will use the default theme instead of the `AppCompat` defined theme. It will basically fall back to Holo. It would be nice if the library was using `android.support.v7.app.AlertDialog` instead of `android.app.AlertDialog` and add a way to tweak the theme for all versions (it's currently locked for lollipop and above for some reason https://github.com/hotchemi/Android-Rate/blob/209f94717a8af7ed6d6095d5dfb32d27f5ec73ca/library/src/main/java/hotchemi/android/rate/Utils.java#L22)

**Comment by hotchemi** [comment]
Thanks and sorry for the late.
Well, would u be able to send a pull request? If not, I'm gonna fix that.

**Comment by mudar** [comment]
I've sent a pull request that uses `android.support.v7.app.AlertDialog ` and adds 
```
AppRate.with(activity).setDialogStyle(R.style.MyCustomStyle)
```
the custom style addition is based on previous PR by @swellner

**Comment by sajid-hussain** [comment]
i have following error
failed to resolve com.github.hotchemi:android-rate:{latest.version}

**Comment by AlexanderLS** [comment]
Hi @sajid-hussain ,

Try to use

    dependencies {
        implementation "com.vorlonsoft:androidrate:1.2.0"
    }
