### ISSUE TITLE
Is it possible to not show the NEVER button?

### ISSUE THREAD

**Issue by sandro-csimas** [hotchemi/Android-Rate#88]
I want to show only "RATE NOW" and "REMIND LATER".
Is it possible?
If not, what do you think of this feature?

**Comment by hotchemi** [comment]
Currently we have no option for the negative button(when it comes to neutral button, we have).

> If not, what do you think of this feature?
I think it's fine. Would you mind send me a pull request?

**Comment by sandro-csimas** [comment]
Nice! I will send you a pull request soon.
