### ISSUE TITLE
How to know which decision user taken? I want to change the AppRate settings at runtime.

### ISSUE THREAD

**Issue by sandro-csimas** [hotchemi/Android-Rate#90]
It will be nice if i can get to know what decision the user has taken.
I'm trying to do the follow:
- Set the install days to 7;
- When the rate dialog is displayed to user and he decided to rate later, i want to increase the remind interval to 15 days.

I think in something like this:
````
rateDialog = AppRate.with(this).setInstallDays(7).setCancelable(true);
if(rateDialog.isRemindLater()) {
  rateDialog.setRemindInterval(15);
} else {
  rateDialog.setRemindInterval(7);
}
// OR
if(rateDialog.getUserDecision().equals(UserDecision.REMIND_LATER)) {
  rateDialog.setRemindInterval(15);
} else {
  rateDialog.setRemindInterval(7);
}
rateDialog.monitor();
````

**Comment by hotchemi** [comment]
:eyes:

**Comment by sandro-csimas** [comment]
@hotchemi??? \o/

**Comment by hotchemi** [comment]
Sorry for the late, I think you can use OnClickButtonListener. onClickButton's argument shows which button is pressed.

https://github.com/hotchemi/Android-Rate/blob/master/library/src/main/java/hotchemi/android/rate/OnClickButtonListener.java#L5

refs. http://developer.android.com/intl/ja/reference/android/content/DialogInterface.html#BUTTON_POSITIVE

**Comment by sandro-csimas** [comment]
The problem is that this is information is not stored in any place. When the activity is created again, i don't have this information anymore. I think it will be nice if the lib store this information.

**Comment by sandro-csimas** [comment]
When the user clicks, the AppRate could store this in its shared preferences.

**Comment by sandro-csimas** [comment]
In my case i will only show the "REMIND LATER" and the "RATE NOW" buttons. When is the first time that the dialog is displayed, the remind interval could be 0 for example. After "REMIND LATER" click i want to increase the interval to 15 days.

**Comment by hotchemi** [comment]
I think you can do it by yourself right? I can implement that but not so much people want that feature and I wanna keep this library simple!

**Comment by sandro-csimas** [comment]
It's very simple, but ok.
