### ISSUE TITLE
File size increased 

### ISSUE THREAD

**Issue by ashishkumawat** [hotchemi/Android-Rate#96]
My App apk size was 1.38mb after using this library its became 5.4mb. Any way to reduce file size.

**Comment by hotchemi** [comment]
aar is only 34.9k. I think you added another one at the same time.

http://search.maven.org/#artifactdetails%7Ccom.github.hotchemi%7Candroid-rate%7C1.0.0%7Caar

**Comment by ashishkumawat** [comment]
Thanks for your quick answer. I will check it.
