### ISSUE TITLE
Runtime Exception: You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by namannik** [hotchemi/Android-Rate#99]
The library crashes when attempting to show the rate dialog.  The crash says:

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.heartv/com.heartvApp.hearTVactivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```
Here's the crash report:

https://fabric.io/heartv/android/apps/com.heartv/issues/56fb1a58ffcdc042503e3436

Any ideas how I can resolve this?  (My activity called `hearTVactivity` extends `FragmentActivity`.)

**Comment by namannik** [comment]
I've fixed this issue in my app by changing my app's theme to `android:theme="@style/Theme.AppCompat.Light"` in the `application` section of `AndroidManifest.xml`.

**Comment by hotchemi** [comment]
Umm, I'll investigate.

**Comment by hotchemi** [comment]
Could you check with 1.0.1?

**Comment by namannik** [comment]
Yes, that fixed the problem.  Thanks!
